name: CraftionsExtentions
version: ${project.version}
main: net.craftions.extensions.Extensions
api-version: 1.16
authors: [ MCTzOCK ]
website: https://extensions.craftions.net
softdepend:
  - CraftionsApi
commands:
  cex:
    usage: /cex <install|remove|update|upgrade> [package] [version]
    permission: craftions.command.cex